// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgylgdssqgjntllpxzjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneWxnZHNzcWdqbnRsbHB4empmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjk3MDMsImV4cCI6MjA3MjMwNTcwM30.3Pwyuz9_A-1vTw1gEWCgZ2kzDS0zCtiTXdu96xunj6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});